#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/k8s

proxy: ""
rke2_server_url: "https://{{ vip if vip is defined and vip != '' else hostvars[group['rke2-master'][0]].ansible_host }}:9345"
rke2_tls_san: []
cni: cilium

rke2_version: v1.33.4+rke2r1
rke2_images_core_url: https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2-images-core.linux-amd64.tar.gz
rke2_binary_url: https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2.linux-amd64.tar.gz
rke2_images_canal_url: https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2-images-canal.linux-amd64.tar.gz
rke2_images_cilium_url: https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/rke2-images-cilium.linux-amd64.tar.gz
rke2_sha256sum_url: https://github.com/rancher/rke2/releases/download/{{ rke2_version }}/sha256sum-amd64.txt
rke2_install_script_url: https://get.rke2.io
