#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/docker

- name: Check if docker is installed
  command: which docker
  register: docker_check
  ignore_errors: true

- block:
    - name: Install docker block
      include_tasks: install_docker.yml
  when: docker_check.rc != 0
