apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-config
data:
  POSTGRES_USER: "postgres"
  POSTGRES_HOST: "192.168.56.110"
  POSTGRES_PORT: "9999"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  KAFKA_BROKERS: "192.168.56.131:9092"
  KAFKA_SASL_MECHANISM: "none"
  KAFKA_CLIENT_USER: "user"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  REDIS_ADDRS: "192.168.56.131:6379"


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
data:
  INFLUXDB_IP: "192.168.56.141"
  INFLUXDB_PORT: "8086"
  INFLUXDB_DATABASE: "telegraf"
  INFLUXDB_USERNAME: "influx"
