apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  POSTGRES_PASSWORD: "YXBwUGFzc3dk" # Base64 encoded: echo -n "put password here" | base64

---
apiVersion: v1
kind: Secret
metadata:
  name: kafka-secret
type: Opaque
data:
  KAFKA_CLIENT_PASSWORD: "cGFzc3dvcmQ=" # Base64 encoded: echo -n "put password here" | base64
