vip: 192.168.56.110

pcp_username: pgpool
device_interface: enp0s8

pg_allowed_ips:
  - 192.168.56.0/24

pg_allowed_user_db:
  - db: sso
    user: application
    table_privilege: "SELECT,INSERT,UPDATE,DELETE"
    sequence_privilege: "USAGE,SELECT,UPDATE"
  - db: sso
    user: readonly
    table_privilege: "SELECT"
    sequence_privilege: "USAGE,SELECT"

  - db: boilerplate
    user: application
    table_privilege: "SELECT,INSERT,UPDATE,DELETE"
    sequence_privilege: "USAGE,SELECT,UPDATE"
  - db: boilerplate
    user: readonly
    table_privilege: "SELECT"
    sequence_privilege: "USAGE,SELECT"

# postgresql config 
# references: 
#   - pgtune.leopard.in.ua 
#   - pgconfig.org
#   - pgconfigurator.cybertec.at
pg_conf_max_connection: 200
pg_conf_shared_buffers: 1GB
pg_conf_effective_cache_size: 3GB
pg_conf_maintenance_work_mem: 256MB
pg_conf_checkpoint_completion_target: 0.9
pg_conf_wal_buffers: 16MB
pg_conf_default_statistics_target: 100
pg_conf_random_page_cost: 1.1
pg_conf_effective_io_concurrency: 200
pg_conf_work_mem: 5140kB
pg_conf_huge_pages: off
pg_conf_min_wal_size: 1GB
pg_conf_max_wal_size: 4GB
pg_conf_max_worker_processes: 4
pg_conf_max_parallel_workers_per_gather: 2
pg_conf_max_parallel_workers: 4
pg_conf_max_parallel_maintenance_workers: 2
pg_conf_ssl: on
pg_conf_include_dir: conf.d

pgpool_conf_num_init_children: 40
pgpool_conf_max_pool: 4
