es:
  hosts:
    es-01:
      ansible_host: 192.168.56.151
      node_name: es_01
      node_roles: ["master", "data_hot"]
    es-02:
      ansible_host: 192.168.56.152
      node_name: es_02
      node_roles: ["master", "data_hot"]
    es-03:
      ansible_host: 192.168.56.153
      node_name: es_03
      node_roles: ["master", "data_warm"]

  vars:
    # tell every SSH connection in this play to skip hostâ€‘key checking
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
