services:
  kafka-kraft:
    image: bitnami/kafka:3.8
    container_name: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9095:9095"
      - "7071:7071"
    environment:
      # configuration is written to: /opt/bitnami/kafka/config/kraft/server.properties
      ALLOW_PLAINTEXT_LISTENER: yes
      # KRaft settings
      KAFKA_CFG_NODE_ID: 0
      KAFKA_CFG_PROCESS_ROLES: controller,broker
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@kafka-kraft:9093
      ## Listener
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,INTERNAL://:9094,SASL_PLAINTEXT://:9095
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:SASL_PLAINTEXT,INTERNAL:PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://172.17.0.1:9092,INTERNAL://:9094,SASL_PLAINTEXT://172.17.0.1:9095

      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CLIENT_LISTENER_NAME: SASL_PLAINTEXT # Remove this line if consumer/producer.properties are not required
      # SASL
      KAFKA_CFG_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
      KAFKA_CFG_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_CONTROLLER_USER: controller_user
      KAFKA_CONTROLLER_PASSWORD: controller_password
      #KAFKA_INTER_BROKER_USER: interbroker_user
      #KAFKA_INTER_BROKER_PASSWORD: interbroker_password
      KAFKA_CLIENT_USERS: user
      KAFKA_CLIENT_PASSWORDS: password

      # config
      KAFKF_CFG_LOG_RETENTION_HOURS: 168 # 7 days
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true

      KAFKA_JMX_PORT: "7071"
      EXTRA_ARGS: "-javaagent:/opt/bitnami/kafka/jmx_exporter/jmx_prometheus_javaagent.jar=7071:/opt/bitnami/kafka/jmx_exporter/kafka_jmx_config.yml"
    volumes:
      - ./jmx_prometheus_javaagent-1.1.0.jar:/opt/bitnami/kafka/jmx_exporter/jmx_prometheus_javaagent.jar  #https://github.com/prometheus/jmx_exporter/releases/tag/1.1.0
      - ./kafka_jmx_config.yml:/opt/bitnami/kafka/jmx_exporter/kafka_jmx_config.yml
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
