- name: Deploy storageclass local-path-provisioner
  shell: |
    kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.32/deploy/local-path-storage.yaml
  register: result
- name: Show result of deploy storageclass local-path-provisioner
  debug: 
    var: result

