#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/k8s

proxy: ""
rke2_server_url: "https://{{ vip if vip is defined and vip != '' else hostvars[group['rke2-master'][0]].ansible_host }}:9345"
rke2_tls_san: []
cni: canal
