#SPDX-License-Identifier: MIT-0
---
# defaults file for roles/postgresql-ha-pgpool2

pgdg_key_url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
pgdg_key_dest: /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc
pgdg_repo_file: /etc/apt/sources.list.d/pgdg.list
pgdg_repo: https://apt.postgresql.org/pub/repos/apt

pgpool_conf_num_init_children: 32
pgpool_conf_max_pool: 4

proxy: ''

exporter_deploy_dir: '/u01/exporter'

cidr_prefix: 24
