environment: dev

serviceName: boilerplate
servicePort: 8001
logLevel: INFO
logPath: logs/app.log

redisAddrs: 192.168.56.131:6379
redisPassword:
redisChannel:
redisPoolSize: 20

kafkaGroupId: boilerplate
kafkaPoolSize: 30
kafkaSignupUserTopic: register

db:
  name: boilerplate

statsdAddr: 192.168.101.14:8125
statsdPrefix: boilerplate_prefix
statsdFlushPeriod: 100

container:
  name: boilerplate-be
  port: 8001
  image: docker.io/duyle95/golang-boilerplate-be
  tag: v1
replicas: 3

# imageCredentials:
registry: docker.io
registryUsername: duyle95
