$ANSIBLE_VAULT;1.1;AES256
37616166353732616138356563383330303335656439393236323832666334326166336134383535
3035643333303364326664646137363636353661613030610a383265326331363434303036363835
39386531646534306236323335383739656364396231333333303532663936393638636261383139
6366333465326630640a346662373265333962353638326437396564323864366338383665646362
39663263353837386563643561646637666264613036363334303133643366356431623339376266
30336366646166633462363236613666626332396431653763303232663636343733643131643831
61316431613932636433316362306436653936643136326232363633383735323237373331663838
32333862363139646438313338353363653663323930393965643166386631313138623663653865
63386566313637366432316336346466626131386162633935383830623237353364316666653762
38666463376237376564646134383263366235353132623832343131626532613161393333376134
63396435663130306433646533343766343966363564356638396164306539363433616563323964
61636130326531663364323539363734323735666630626563636162383262333837383332343165
32346234363663313932633165626230383937346133343432303561336337323830326262346565
30303363353665633431653261346630626163393839363931616130613432326162373832653764
37666435356131366639363266306630383761316366343061626565363365303834626662386339
66303032366131613238316365373261656161333464343537303038383630393434306233353061
34376139383330666463366466613133656135663965383230373634323233376437
