master:
  hosts:
    es-master-01:
      ansible_host: 192.168.56.151
      node_name: es-01 
      node_roles:A 

data:
  hosts:
    es-02:
      ansible_host: 192.168.56.202
      node_name: es-02
    
    es-03:
      ansible_host: 192.168.56.202
      node_name: es-03

k8s:
  children:
    k8s-master: {}
    k8s-worker: {}

  vars:
    # tell every SSH connection in this play to skip hostâ€‘key checking
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
