all:
  hosts:
    node-monitor-01:
      ansible_host: 192.168.56.141
      node_name: node-monitor-01
  vars:
    # tell every SSH connection in this play to skip hostâ€‘key checking
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
    ansible_user: vagrant
