apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.container.name }}
  labels:
    app: {{ .Values.container.name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.container.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.container.name }} # pod labels
        environment: {{ .Values.environment }}
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      volumes:
        - name: private-keys
          secret:
            secretName: be-private-keys
      containers:
        - name: {{ .Values.container.name }}
          image: {{ .Values.container.image }}:{{ .Values.container.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.container.port }}
          volumeMounts:
              # private key
            - name: private-keys
              mountPath: /src/certs
              readOnly: true
          livenessProbe:
            httpGet:
              path: /api/healthz
              port: {{ .Values.container.port }}
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /api/healthz
              port: {{ .Values.container.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: SERVICE_ENV
              value: {{ .Values.environment | quote }}
            - name: SERVICE_NAME
              value: {{ .Values.serviceName | quote }}
            - name: SERVICE_PORT
              value: {{ .Values.servicePort | quote }}

            - name: LOG_LEVEL
              value: {{ .Values.logLevel | quote }}
            - name: LOG_PATH
              value: {{ .Values.logPath | quote }}

            - name: REDIS_ADDRS
              value: {{ .Values.redisAddrs | quote }}
            - name: REDIS_PASSWORD
              value: {{ .Values.redisPassword | quote }}
            - name: REDIS_CHANNEL
              value: {{ .Values.redisChannel | quote }}
            - name: REDIS_POOL_SIZE
              value: {{ .Values.redisPoolSize | quote }}

            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_BROKERS
            - name: KAFKA_CLIENT_USER
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_CLIENT_USER
            - name: KAFKA_CLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-secret
                  key: KAFKA_CLIENT_PASSWORD
            - name: KAFKA_GROUP_ID
              value: {{ .Values.kafkaGroupId | quote }}
            - name: KAFKA_POOL_SIZE
              value: {{ .Values.kafkaPoolSize | quote }}
            - name: KAFKA_SIGNUP_USER_TOPIC
              value: {{ .Values.kafkaSignupUserTopic | quote }}
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: KAFKA_SASL_MECHANISM

            - name: STATSD_ADDR
              value: {{ .Values.statsdAddr | quote }}
            - name: STATSD_PREFIX
              value: {{ .Values.statsdPrefix | quote }}
            - name: STATSD_FLUSH_PERIOD
              value: {{ .Values.statsdFlushPeriod | quote }}

            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_HOST
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_PORT
            - name: POSTGRES_DBNAME
              value: {{ .Values.db.name | quote }}
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: postgresql-config
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-secret
                  key: POSTGRES_PASSWORD

